#include "UINativeTags.h"

#ifndef LAYERS
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_GAME, "UI.Layer.Game");
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_MENUSCREEN, "UI.Layer.MenuScreen");
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_MODAL, "UI.Layer.Modal");
UE_DEFINE_GAMEPLAY_TAG(TAG_UI_LAYER_ERROR, "UI.Layer.Error");
#endif // LAYERS