#pragma once

#include "NativeGameplayTags.h"

#pragma region Layers
WOWUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_GAME);
WOWUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_MENUSCREEN);
WOWUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_MODAL);
WOWUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_ERROR);
#pragma endregion Layers

#pragma region Actions
WOWUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_ACTION_ESCAPE);
#pragma endregion Actions;