#pragma once

#include "NativeGameplayTags.h"

#ifndef LAYERS
WOWUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_GAME);
WOWUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_MENUSCREEN);
WOWUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_MODAL);
WOWUI_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_ERROR);
#endif // LAYERS