#pragma once

#include "NativeGameplayTags.h"

WOWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAME_EVENT_NAMEPLATE_VISIBILITY);
WOWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GAME_EVENT_TARGET_SELECTED);
